 platform :ios, '11.0'

target 'AppAuthentication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  # Pods for AppAuthentication
end
